[email]
sender = "uchinthalasupriya@gmail.com"
password = "fwrrthjsfwnxcbpk"

[stripe]
api_key = "your_stripe_key"

[zoom]
api_key = "your_zoom_key"
api_secret = "your_zoom_secret"
account_id = "your_account_id"
[supabase]
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZmxpdmxrd2h6dHFqZnl1eHplIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDMwNDY4MiwiZXhwIjoyMDU1ODgwNjgyfQ.8qe91dnzpTkgzLoMDCCANrI70ZjnqKr8Ni_ehDLWZhc"